"""Generate the two figures embedded in docs/nano_protocol_study_results.md.

Transparent background (reads on GitHub light *and* dark themes), amber+forest
palette, minimal labels. Two figures only:

  * capability.png     pre-merge capability vs post-merge merge-clean, per arm
  * merge_failures.png  where each pair-run lands after the naive merge

Numbers are transcribed from the reviewed tables in the results doc (§3, §5, §7),
themselves generated by scripts/nano/analyze_study.py.

Run:  uv run --with matplotlib python scripts/nano/make_figures.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "figures" / "nano_study"
OUT.mkdir(parents=True, exist_ok=True)

# palette — bright enough to read on a dark surface, muted enough for light
FOREST = "#5FA06B"  # coordination / honest pass
AMBER = "#E8A83A"  # capability / solo_rescue
BRONZE = "#C77D3A"  # functional_fail
TAUPE = "#8A7256"  # textual_conflict
GRAY = "#9A9284"  # missing_patch

INK = "#B9B3A5"  # neutral text — legible on both themes
GRIDC = "#8A8A8A"

mpl.rcParams.update(
    {
        "font.family": "DejaVu Sans",
        "font.size": 12,
        "text.color": INK,
        "axes.labelcolor": INK,
        "axes.titlecolor": INK,
        "xtick.color": INK,
        "ytick.color": INK,
        "figure.facecolor": "none",
        "axes.facecolor": "none",
        "savefig.transparent": True,
    }
)

ARMS = ["control", "free-text", "semi", "handshake", "coder", "coauthor"]

# pre-merge capability (§7): agent solves its own feature in isolation
CAPABILITY = [75, 70, 79, 87, 82, 81]
# post-merge merge-clean (§3)
MERGECLEAN = [13, 21, 16, 20, 18, 78]

# failure taxonomy (§5): pass, solo_rescue, functional_fail, textual_conflict, missing_patch
TAXO_LABELS = ["passed", "solo-rescue", "func-fail", "conflict", "no-patch"]
TAXO_COLORS = [FOREST, AMBER, BRONZE, TAUPE, GRAY]
TAXONOMY = [
    [2, 0, 1, 87, 11],
    [3, 0, 1, 79, 17],
    [3, 0, 2, 84, 11],
    [10, 0, 3, 80, 7],
    [5, 43, 0, 39, 14],
    [62, 6, 10, 17, 6],
]


def _bare(ax):
    ax.set_ylim(0, 100)
    ax.set_yticks([0, 50, 100])
    ax.set_yticklabels(["0", "50", "100%"])
    ax.tick_params(length=0)
    ax.grid(axis="y", color=GRIDC, alpha=0.25, linewidth=0.8)
    ax.set_axisbelow(True)
    for s in ax.spines.values():
        s.set_visible(False)


# ---------------------------------------------------------------------------
# Fig 1 — capability (pre-merge) vs merge-clean (post-merge)
# ---------------------------------------------------------------------------
def fig_capability():
    fig, ax = plt.subplots(figsize=(8.0, 4.2))
    x = list(range(len(ARMS)))
    w = 0.38
    ax.bar([i - w / 2 for i in x], CAPABILITY, w, color=AMBER, label="builds own feature (pre-merge)")
    ax.bar([i + w / 2 for i in x], MERGECLEAN, w, color=FOREST, label="patches merge clean (post-merge)")
    for i in x:
        ax.text(i - w / 2, CAPABILITY[i] + 2, f"{CAPABILITY[i]}", ha="center", va="bottom", fontsize=10, color=AMBER)
        ax.text(i + w / 2, MERGECLEAN[i] + 2, f"{MERGECLEAN[i]}", ha="center", va="bottom", fontsize=10, color=FOREST)
    _bare(ax)
    ax.set_xticks(x)
    ax.set_xticklabels(ARMS, fontsize=11)
    ax.set_title("Capability is high; coordination is the gap", fontsize=14, fontweight="bold", pad=28, loc="left")
    ax.legend(frameon=False, loc="upper left", bbox_to_anchor=(0, 1.10), fontsize=10.5, handlelength=1.1, ncol=1)
    fig.tight_layout()
    fig.savefig(OUT / "capability.png", dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Fig 2 — why the merge fails (stacked taxonomy)
# ---------------------------------------------------------------------------
def fig_failures():
    fig, ax = plt.subplots(figsize=(8.0, 4.6))
    x = list(range(len(ARMS)))
    bottom = [0.0] * len(ARMS)
    for j, col in enumerate(TAXO_COLORS):
        vals = [TAXONOMY[i][j] for i in range(len(ARMS))]
        ax.bar(x, vals, bottom=bottom, color=col, width=0.7)
        for i, v in enumerate(vals):
            if v >= 12:
                ax.text(i, bottom[i] + v / 2, f"{v}", ha="center", va="center", fontsize=10, color="#1c1c1c")
        bottom = [b + v for b, v in zip(bottom, vals)]
    _bare(ax)
    ax.set_xticks(x)
    ax.set_xticklabels(ARMS, fontsize=11)
    ax.set_title("Why the merge fails", fontsize=14, fontweight="bold", pad=30, loc="left")
    handles = [Patch(facecolor=c, label=lbl) for lbl, c in zip(TAXO_LABELS, TAXO_COLORS)]
    ax.legend(
        handles=handles,
        frameon=False,
        ncol=5,
        fontsize=10,
        loc="lower center",
        bbox_to_anchor=(0.5, 1.0),
        handlelength=1.0,
        columnspacing=1.1,
        handletextpad=0.5,
    )
    fig.tight_layout()
    fig.savefig(OUT / "merge_failures.png", dpi=150, bbox_inches="tight")
    plt.close(fig)


if __name__ == "__main__":
    fig_capability()
    fig_failures()
    print("wrote:", ", ".join(sorted(p.name for p in OUT.glob("*.png"))))
