"""Generate the figures embedded in docs/nano_protocol_study_results.md.

Amber + forest palette, held consistent across all four figures:
  * forest  = merge-clean (primary) / honest `pass`   — the real metric
  * amber   = both_passed (secondary) / `solo_rescue`  — looks-good-but-watch-out

Numbers are transcribed from the reviewed tables in the results doc (§3, §5,
appendix), which are themselves generated by scripts/nano/analyze_study.py.

Run:  uv run --with matplotlib python scripts/nano/make_figures.py
Out:  docs/figures/nano_study/{primary,divergence,taxonomy,heatmap}.png
"""

from __future__ import annotations

from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.patches import Patch

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "figures" / "nano_study"
OUT.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------------------
# palette
# ----------------------------------------------------------------------------
FOREST_DEEP = "#2E5D3B"  # merge-clean / honest pass — the real win
FOREST = "#4A7C59"
SAGE = "#8FAE7B"
AMBER = "#E0982E"  # both_passed / solo_rescue — the artifact / caution
AMBER_LIGHT = "#F2C572"
BRONZE = "#B5651D"  # functional_fail
BROWN = "#5E4632"  # textual_conflict (muted)
WARMGRAY = "#BDB4A3"  # missing_patch

INK = "#33302A"  # primary text
MUTED = "#6E675C"  # secondary text
GRID = "#E7E1D6"
SURFACE = "#FDFCF9"

mpl.rcParams.update(
    {
        "figure.facecolor": SURFACE,
        "axes.facecolor": SURFACE,
        "savefig.facecolor": SURFACE,
        "font.family": "DejaVu Sans",
        "font.size": 11,
        "text.color": INK,
        "axes.edgecolor": GRID,
        "axes.labelcolor": INK,
        "axes.titlecolor": INK,
        "xtick.color": MUTED,
        "ytick.color": MUTED,
        "axes.grid": True,
        "grid.color": GRID,
        "grid.linewidth": 0.9,
        "axes.axisbelow": True,
    }
)

# ----------------------------------------------------------------------------
# data (from docs/nano_protocol_study_results.md §3, §5, appendix)
# ----------------------------------------------------------------------------
ARMS = [
    "no-msg\n(control)",
    "free-text",
    "semi_\nstructured",
    "plan_\nhandshake",
    "designated_\ncoder",
    "coauthor_\noverlap",
]

# merge-clean (primary): rate, ci_lo, ci_hi
PRIMARY = [
    (13, 10, 18),
    (21, 17, 26),
    (16, 12, 21),
    (20, 16, 25),
    (18, 12, 28),
    (78, 68, 85),
]
# both_passed (secondary): rate, ci_lo, ci_hi
SECONDARY = [
    (2, 1, 4),
    (3, 2, 6),
    (3, 2, 6),
    (10, 7, 15),
    (58, 48, 68),
    (69, 58, 77),
]

# failure taxonomy (§5): pass, solo_rescue, functional_fail, textual_conflict, missing_patch
TAXO_LABELS = ["pass", "solo_rescue", "functional_fail", "textual_conflict", "missing_patch"]
TAXO_COLORS = [FOREST_DEEP, AMBER, BRONZE, BROWN, WARMGRAY]
TAXONOMY = [
    [2, 0, 1, 87, 11],
    [3, 0, 1, 79, 17],
    [3, 0, 2, 84, 11],
    [10, 0, 3, 80, 7],
    [5, 43, 0, 39, 14],
    [62, 6, 10, 17, 6],
]

# per-pair merge-clean (appendix): 18 pairs x 6 arms
PAIR_LABELS = [
    "dottxt_outlines/1371 (1,2)",
    "dottxt_outlines/1655 (8,10)",
    "dspy/8394 (3,5)",
    "dspy/8587 (4,5)",
    "dspy/8635 (1,3)",
    "hf_datasets/3997 (1,5)",
    "llama_index/17070 (1,3)",
    "llama_index/17244 (3,5)",
    "tiktoken/0 (2,6)",
    "click/2068 (1,6)",
    "click/2800 (1,7)",
    "jinja/1465 (1,8)",
    "jinja/1559 (2,4)",
    "jinja/1621 (1,6)",
    "pillow/25 (3,4)",
    "pillow/68 (2,3)",
    "pillow/290 (3,4)",
    "dirty_equals/43 (5,7)",
]
HEAT_ARMS = ["control", "free", "struct", "handshake", "dc", "coauthor"]
HEAT = [
    [7, 20, 0, 7, 0, 80],
    [13, 27, 20, 7, 40, 80],
    [7, 20, 7, 7, 20, 80],
    [7, 20, 0, 13, 60, 60],
    [27, 40, 33, 60, 20, 75],
    [7, 40, 40, 87, 25, 60],
    [7, 13, 13, 0, 25, 80],
    [7, 13, 13, 53, 0, 40],
    [7, 13, 13, 0, 0, 100],
    [13, 20, 13, 0, 20, 100],
    [13, 20, 13, 27, 40, 80],
    [13, 13, 13, 0, 0, 100],
    [13, 13, 13, 33, 40, 100],
    [13, 13, 13, 0, 0, 40],
    [47, 47, 33, 13, 20, 100],
    [13, 13, 13, 13, 0, 100],
    [13, 20, 20, 27, 20, 60],
    [13, 13, 13, 13, 0, 60],
]


def _style_axes(ax, ymax=100):
    ax.set_ylim(0, ymax)
    ax.set_yticks(range(0, ymax + 1, 20))
    ax.set_yticklabels([f"{y}%" for y in range(0, ymax + 1, 20)])
    ax.xaxis.grid(False)
    ax.tick_params(length=0)
    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    ax.spines["bottom"].set_color(GRID)


# ----------------------------------------------------------------------------
# Fig 1 — primary endpoint (merge-clean) with Wilson CIs
# ----------------------------------------------------------------------------
def fig_primary():
    fig, ax = plt.subplots(figsize=(8.2, 4.6))
    x = range(len(ARMS))
    rates = [p[0] for p in PRIMARY]
    lo = [p[0] - p[1] for p in PRIMARY]
    hi = [p[2] - p[0] for p in PRIMARY]
    # winner deep forest, floor arms sage — encodes the merge-clean metric, not rank
    colors = [SAGE] * 5 + [FOREST_DEEP]
    ax.bar(x, rates, color=colors, width=0.62, zorder=3)
    ax.errorbar(x, rates, yerr=[lo, hi], fmt="none", ecolor=INK, elinewidth=1.4, capsize=4, capthick=1.4, zorder=4)
    for xi, r in zip(x, rates):
        ax.text(
            xi, r + max(hi) * 0.06 + 3, f"{r}%", ha="center", va="bottom", fontsize=11, fontweight="bold", color=INK
        )
    _style_axes(ax)
    ax.set_xticks(list(x))
    ax.set_xticklabels(ARMS, fontsize=9.5)
    ax.set_title(
        "Primary endpoint — merge-clean rate by protocol", fontsize=13.5, fontweight="bold", pad=12, loc="left"
    )
    ax.text(
        0,
        1.015,
        "Two independent patches combine without conflict (no-git coop, 18 validated pairs, Wilson 95% CI)",
        transform=ax.transAxes,
        fontsize=9.5,
        color=MUTED,
    )
    ax.axhline(13, color=AMBER, lw=1.1, ls=(0, (4, 3)), zorder=2)
    ax.text(len(ARMS) - 0.5, 15.5, "control floor 13%", ha="right", va="bottom", fontsize=8.5, color=BRONZE)
    fig.tight_layout()
    fig.savefig(OUT / "primary.png", dpi=150, bbox_inches="tight")
    plt.close(fig)


# ----------------------------------------------------------------------------
# Fig 2 — primary vs secondary divergence
# ----------------------------------------------------------------------------
def fig_divergence():
    fig, ax = plt.subplots(figsize=(8.2, 4.6))
    x = list(range(len(ARMS)))
    w = 0.38
    prim = [p[0] for p in PRIMARY]
    sec = [s[0] for s in SECONDARY]
    ax.bar([xi - w / 2 for xi in x], prim, width=w, color=FOREST_DEEP, zorder=3, label="merge-clean (primary)")
    ax.bar([xi + w / 2 for xi in x], sec, width=w, color=AMBER, zorder=3, label="both_passed (secondary)")
    for xi in x:
        ax.text(xi - w / 2, prim[xi] + 2, f"{prim[xi]}", ha="center", va="bottom", fontsize=8.5, color=FOREST_DEEP)
        ax.text(xi + w / 2, sec[xi] + 2, f"{sec[xi]}", ha="center", va="bottom", fontsize=8.5, color=BRONZE)
    _style_axes(ax)
    ax.set_xticks(x)
    ax.set_xticklabels(ARMS, fontsize=9.5)
    ax.set_title(
        "Primary vs secondary — the solo_rescue divergence", fontsize=13.5, fontweight="bold", pad=12, loc="left"
    )
    ax.text(
        0,
        1.015,
        "designated_coder scores high on both_passed but not on merge-clean: its wins are solo_rescue, not merges",
        transform=ax.transAxes,
        fontsize=9.5,
        color=MUTED,
    )
    # annotate the gap on designated_coder
    ax.annotate(
        "40-pt gap\n= solo_rescue",
        xy=(4, 45),
        xytext=(3.05, 62),
        fontsize=8.5,
        color=BRONZE,
        ha="center",
        arrowprops=dict(arrowstyle="->", color=BRONZE, lw=1.1),
    )
    ax.legend(frameon=False, loc="upper left", fontsize=9.5, handlelength=1.1, bbox_to_anchor=(0.0, 0.95))
    fig.tight_layout()
    fig.savefig(OUT / "divergence.png", dpi=150, bbox_inches="tight")
    plt.close(fig)


# ----------------------------------------------------------------------------
# Fig 3 — failure taxonomy (stacked)
# ----------------------------------------------------------------------------
def fig_taxonomy():
    fig, ax = plt.subplots(figsize=(8.2, 4.8))
    x = list(range(len(ARMS)))
    bottom = [0.0] * len(ARMS)
    for j, (lbl, col) in enumerate(zip(TAXO_LABELS, TAXO_COLORS)):
        vals = [TAXONOMY[i][j] for i in range(len(ARMS))]
        ax.bar(x, vals, bottom=bottom, color=col, width=0.66, zorder=3, label=lbl, edgecolor=SURFACE, linewidth=1.2)
        # label the large segments
        for i, v in enumerate(vals):
            if v >= 12:
                ax.text(
                    i,
                    bottom[i] + v / 2,
                    f"{v}%",
                    ha="center",
                    va="center",
                    fontsize=8.5,
                    color="white" if col in (FOREST_DEEP, BROWN, BRONZE) else INK,
                    fontweight="bold",
                )
        bottom = [b + v for b, v in zip(bottom, vals)]
    _style_axes(ax)
    ax.set_xticks(x)
    ax.set_xticklabels(ARMS, fontsize=9.5)
    ax.set_title("Failure taxonomy by protocol", fontsize=13.5, fontweight="bold", pad=12, loc="left")
    ax.text(
        0,
        1.015,
        "Where each pair-run lands after the naive merge (validated set). Forest = honest pass; amber = solo_rescue",
        transform=ax.transAxes,
        fontsize=9.5,
        color=MUTED,
    )
    handles = [Patch(facecolor=c, label=lbl) for lbl, c in zip(TAXO_LABELS, TAXO_COLORS)]
    ax.legend(
        handles=handles,
        frameon=False,
        ncol=5,
        fontsize=8.8,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.22),
        handlelength=1.1,
        columnspacing=1.2,
    )
    fig.tight_layout()
    fig.savefig(OUT / "taxonomy.png", dpi=150, bbox_inches="tight")
    plt.close(fig)


# ----------------------------------------------------------------------------
# Fig 4 — per-pair merge-clean heatmap
# ----------------------------------------------------------------------------
def fig_heatmap():
    cmap = LinearSegmentedColormap.from_list("amber_forest", ["#FBF3E2", AMBER_LIGHT, SAGE, FOREST_DEEP])
    fig, ax = plt.subplots(figsize=(7.4, 8.4))
    ax.imshow(HEAT, aspect="auto", cmap=cmap, vmin=0, vmax=100)
    ax.set_xticks(range(len(HEAT_ARMS)))
    ax.set_xticklabels(HEAT_ARMS, fontsize=10)
    ax.set_yticks(range(len(PAIR_LABELS)))
    ax.set_yticklabels(PAIR_LABELS, fontsize=8.5)
    ax.tick_params(length=0)
    for s in ax.spines.values():
        s.set_visible(False)
    for i in range(len(PAIR_LABELS)):
        for j in range(len(HEAT_ARMS)):
            v = HEAT[i][j]
            ax.text(
                j,
                i,
                f"{v}",
                ha="center",
                va="center",
                fontsize=8,
                color="white" if v >= 55 else INK,
            )
    ax.set_title("Per-pair merge-clean rate", fontsize=13.5, fontweight="bold", pad=10, loc="left")
    ax.text(
        0,
        1.008,
        "18 validated pairs x 6 protocols. Darker forest = higher merge-clean rate",
        transform=ax.transAxes,
        fontsize=9.5,
        color=MUTED,
    )
    ax.set_xticks([x - 0.5 for x in range(1, len(HEAT_ARMS))], minor=True)
    ax.set_yticks([y - 0.5 for y in range(1, len(PAIR_LABELS))], minor=True)
    ax.grid(which="minor", color=SURFACE, linewidth=1.5)
    ax.grid(which="major", visible=False)
    fig.tight_layout()
    fig.savefig(OUT / "heatmap.png", dpi=150, bbox_inches="tight")
    plt.close(fig)


if __name__ == "__main__":
    fig_primary()
    fig_divergence()
    fig_taxonomy()
    fig_heatmap()
    print("wrote:", ", ".join(sorted(p.name for p in OUT.glob("*.png"))))
